apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: car-ingress
  namespace: my-app-prod
spec:
  rules:
    - host: web.car.co.za
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-service-prod
                port:
                  number: 80

