---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: my-app-dev
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          imagePullPolicy: Always
          image: rembun/devops:argocd-website
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret
