apiVersion: v1
kind: Service
metadata:
  name: nginx-service-honey-web
  namespace: my-app-web
spec:
  type: NodePort
  selector:
    app: my-app-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # You can choose any available port between 30000-32767

