apiVersion: v1
kind: Service
metadata:
  name: nginx-service-qa
  namespace: my-app-qa
spec:
  type: LoadBalancer
  selector:
    app: nginx-nfs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30006

