apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs
  namespace: my-app-qa
  labels:
    name: nginx-nfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-nfs
  template:
    metadata:
      labels:
        app: nginx-nfs
    spec:
      containers:
      - name: nginx-nfs
        imagePullPolicy: IfNotPresent
        image: rembun/devops:car-web
        ports:
          - name: web
            containerPort: 80
        volumeMounts:
          - name: nfs-share
            mountPath: /usr/share/nginx/html
      imagePullSecrets:
        - name: dockerhub-argocd
      volumes:
        - name: nfs-share
          persistentVolumeClaim:
            claimName: nfs-pvc
